Negative tests cases for repositories
Dev-incubator/DIMS-Core pull request #10
Opened 2020-10-19 10:10 UTC by SashaDrapun

2020-10-20 10:33 UTC, PushMeNow requested changes
Hello.
I did some comments. You forgot about async methods. Fix it please.

2020-10-20 10:33 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +        public void GetByIdAsync_GetItemByNegativeId_ValueIsNull()
Async??

2020-10-20 10:33 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +        public void GetByIdAsync_GetItemByNegativeId_ValueIsNull()
Async??

2020-10-20 10:33 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +        public void GetByIdAsync_GetItemByNegativeId_ValueIsNull()
Async??

2020-10-20 22:20 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +        public void GetByIdAsync_GetItemByNegativeId_ValueIsNull()
![image](https://user-images.githubusercontent.com/45926089/96650453-9f354a00-133b-11eb-82d8-a989790fcb39.png)

2020-10-20 22:20 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +        public void GetByIdAsync_GetItemByNegativeId_ValueIsNull()
![image](https://user-images.githubusercontent.com/45926089/96650468-a52b2b00-133b-11eb-8dad-0042706c801a.png)

2020-10-20 22:20 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +        public void GetByIdAsync_GetItemByNegativeId_ValueIsNull()
![image](https://user-images.githubusercontent.com/45926089/96650475-aa887580-133b-11eb-9342-93bc9b756b64.png)

2020-10-24 20:50 UTC, maximsan requested changes
Hello! I left some notes, please fix them ASAP. Thanks!

2020-10-24 20:50 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +            var result = await query.GetByIdAsync(getId);
Why do you use this `query` name everywhere ? :) Please, rename

2020-10-24 20:50 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.Task.Count()));
The test is wrong, you should test again hardcoded value
`Assert.That(5, Is.EqualTo(Context.Task.Count()));`

2020-10-24 20:50 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.Direction.Count()));
The test is wrong, you should test again hardcoded value, for example
`Assert.That(5, Is.EqualTo(Context.Task.Count()));`

`Assert.That(expected, Is.EqualTo(actual))`

2020-10-24 20:50 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskStateRepositoryTest.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.TaskState.Count()));
The same mistake is here

2020-10-25 23:25 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.Task.Count()));
Tests are run in random order. If you run all tests and the addition works first, then the test for checking the number of elements with hardcoded value will fail.

2020-10-25 23:26 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.Direction.Count()));
Tests are run in random order. If you run all tests and the addition works first, then the test for checking the number of elements with hardcoded value will fail.

2020-10-25 23:26 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskStateRepositoryTest.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.TaskState.Count()));
Tests are run in random order. If you run all tests and the addition works first, then the test for checking the number of elements with hardcoded value will fail.

2020-10-25 23:35 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +            var result = await query.GetByIdAsync(getId);
![image](https://user-images.githubusercontent.com/45926089/97122044-e05e9d00-1733-11eb-8580-7a4f6ac02932.png)

2020-10-25 23:36 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +            var result = await query.GetByIdAsync(getId);
I already fixed this in another branch, but it turned out that this branch was separated from the first one, before it was fixed in that branch. Now I fixed it in this branch :)

2020-10-26 12:46 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.Direction.Count()));
![image](https://user-images.githubusercontent.com/45926089/97173985-77623e00-17a2-11eb-85c5-88e343d4854b.png)

2020-10-26 12:47 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskStateRepositoryTest.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.TaskState.Count()));
![image](https://user-images.githubusercontent.com/45926089/97174005-82b56980-17a2-11eb-9f58-2f6f32930d51.png)

2020-10-26 12:47 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +            Assert.That(countDirectionsBeforeAdding, Is.EqualTo(Context.Task.Count()));
![image](https://user-images.githubusercontent.com/45926089/97174038-9365df80-17a2-11eb-9e21-60ad3a50428c.png)

2020-10-27 11:01 UTC, PushMeNow requested changes
Hi.
You did one comment. Fix it please.

2020-10-27 11:01 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +            var result = repository.GetByIdAsync(getId);
Await?

2020-10-27 11:21 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +            var result = repository.GetByIdAsync(getId);
![image](https://user-images.githubusercontent.com/45926089/97294891-a68ab500-185f-11eb-9286-b8d79b5dd2ee.png)

2020-10-29 18:03 UTC, maximsan approved these changes
Looks better! One point to think about. I guess you can move you repository disposing logic in common test base class.

2020-10-29 18:29 UTC, PushMeNow approved these changes
Good job

2020-10-31 20:21 UTC, merged