CRUD Task
Dev-incubator/DIMS-Core pull request #12
Opened 2020-10-25 20:34 UTC by leonidbogin

I recreated the pull request, since I added more functionality and changed the logic.
CRUD for assignments is ready. 
It remains only to resolve the issue with the date format. How to choose and how to change default format for the date field.

2020-10-25 21:11 UTC, leonidbogin commented
I will create Task unit tests after reviews of the pull request.

2020-10-25 23:20 UTC, SashaDrapun reviewed
You did a good job! I did not find any strong errors. The only thing is, is it necessary to use css?

2020-10-25 23:20 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/wwwroot/css/site.css
>      z-index: -1;
I don't really understand why to use css and position absolute. How I know "position: absolute" it not good practice

2020-10-25 23:20 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/wwwroot/css/site.css
> +    padding: 7px 10px;
Couldn't it be done with bootstrap? Padding can definitely be set via bootstrap.

2020-10-25 23:20 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +            }
This code looks quite voluminous. Maybe we can move the part into a separate method?

2020-10-26 01:21 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/wwwroot/css/site.css
>      z-index: -1;
This code was before me =). I only added one style (93-97)

2020-10-26 01:26 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/wwwroot/css/site.css
> +    padding: 7px 10px;
I don't know how to do it with bootstrap. I will read about it.

2020-10-27 11:58 UTC, PushMeNow requested changes
Hi.
I did some comments. Please look them through and fix. Pay attention on mapping.

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +using MemberForTaskModel = DIMS_Core.BusinessLayer.Models.Task.MemberForTaskModel;
Why did you write this? Do you have another model with same name?

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +using TaskModel = DIMS_Core.BusinessLayer.Models.Task.TaskModel;
Why did you write this? Do you have another model with same name?

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +using UserTask = DIMS_Core.DataAccessLayer.Entities.UserTask;
Why did you write this? Do you have another model with same name?

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +                         };
Change on extentions. And use mapper. Read about projection in mapper.

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +                        };
User projection in mapper like this
`mapper.ProjectTo<T>({iqueryableExpression})`

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +                        var mappedUserTask = mapper.Map<UserTask>(userTask);
You mustn't use here mapping. Just create UserTask entity. It will be enough.

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +                        var mappedUserTask = mapper.Map<UserTask>(userTask);
You mustn't use here mapping. Just create UserTask entity. It will be enough.

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Models/Task/TaskWithMembersViewModel.cs
> +    public class TaskWithMembersViewModel : TaskViewModel
Models mustn't use inheritance.

2020-10-27 11:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/wwwroot/css/site.css
> +    padding: 7px 10px;
Bootstrap doesn't have definition for checkbox list so it's OK.

2020-10-28 05:03 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +            }
`
                foreach (var member in members)
                {
                    if (member.Selected && member.UserTaskId == 0)
                    {
                        await CreateUserTask(model.TaskId, member.UserId);
                    }
                    else if (!member.Selected && member.UserTaskId > 0)
                    {
                        await DeleteUserTask(member.UserTaskId);
                    }
                }
`

2020-10-28 05:05 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +using MemberForTaskModel = DIMS_Core.BusinessLayer.Models.Task.MemberForTaskModel;
![image](https://user-images.githubusercontent.com/65702576/97394383-5f023880-18f4-11eb-8bb8-0b2bb3d64527.png)

2020-10-28 05:09 UTC, leonidbogin commented
- Created a helper for controllers to keep things simple.
- Fixed approach to work with EF.
- And a more fixes

2020-11-02 08:40 UTC, maximsan reviewed
I left some notes, let's discuss them if I'm wrong somewhere.  Thanks!

2020-11-02 08:40 UTC, maximsan commented on DIMS-Core/DIMS-Core/Helpers/HelperHtml.cs
> +
why  is it empty ?

2020-11-02 08:40 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Filters/UserTaskFilter.cs
> +        }
I guess we don't need a filter, do we ?

2020-11-02 08:40 UTC, maximsan commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +                    else if (!member.Selected && member.UserTaskId > 0)
I guess `UserTaskId != 0`  is more accurate checking in this case.

2020-11-02 18:11 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Helpers/HelperHtml.cs
> +
```suggestion
            string result = "<div class=\"form-control checkbox-list\">\n";
            if (members != null && members.Count > 0)
            {
                for (int i = 0; i < members.Count; i++)
```

2020-11-02 18:13 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.DataAccessLayer/Filters/UserTaskFilter.cs
> +        }
Thanks) I have removed the unnecessary code

2020-11-02 18:19 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +                    else if (!member.Selected && member.UserTaskId > 0)
Thanks. I fixed it.
```suggestion
                    if (member.Selected && member.UserTaskId == 0)
                    {
                        await CreateUserTask(model.TaskId, member.UserId);
                    }
                    else if (!member.Selected && member.UserTaskId != 0)
                    {
                        await DeleteUserTask(member.UserTaskId);
                    }
```

2020-11-02 19:12 UTC, maximsan approved these changes
It seems like everything is fine! Thanks!

2020-11-03 01:08 UTC, leonidbogin commented
I will change the logic of selecting members in the task.

2020-11-03 08:29 UTC, PushMeNow requested changes
Hi dude! :)
I did some comments. Look them through and fix please.

2020-11-03 08:29 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskController.cs
> +            model.Members.MarkSelectedMembersForTask(task.UserTask);                                // Mark members who participates in this task
As we talked: move member list to ViewBag.

2020-11-03 08:29 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskController.cs
> +            model.Members.GetMembersForTask(task.UserTask);                                         // Get list of members who participates in this task
Automapper

2020-11-03 08:29 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Helpers/HelperControllers.cs
> +            foreach (var userTask in userTasks)
Always use brackets.

2020-11-03 08:29 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Helpers/HelperControllers.cs
> +            foreach (var userTask in userTasks)
Always use brackets.

2020-11-03 08:29 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Models/Task/TaskWithMembersViewModel.cs
> +        public TaskWithMembersViewModel(List <MemberForTaskModel> Members)
Use camelcase for local and method variables.

2020-11-03 08:29 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/Task/Delete.cshtml
> +            @if (Model.Description is null) { <div>-</div> }
Don't write block constructions in single row please.

2020-11-03 11:20 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/Task/TaskModel.cs
> +        public virtual ICollection<UserTaskModel> UserTask { get; set; }
```suggestion
        public ICollection<UserTaskModel> UserTask { get; set; }
```

2020-11-03 11:21 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/UserTask/UserTaskModel.cs
> +        public virtual UserProfileModel User { get; set; }
```suggestion
        public UserProfileModel User { get; set; }
```

2020-11-03 11:27 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IMemberService.cs
> +        Task<IEnumerable<VUserProfileModel>> Search();
```suggestion
        Task<IEnumerable<VUserProfileModel>> GetAll();
```

2020-11-03 11:28 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/MemberService.cs
> +        public async Task<IEnumerable<VUserProfileModel>> Search()
public async Task<IEnumerable<VUserProfileModel>> GetAll()

2020-11-03 22:31 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Views/Task/Delete.cshtml
> +            @if (Model.Description is null) { <div>-</div> }
```suggestion
            @if (Model.Description is null)
            {
                <div>-</div> 
            }
            else
            {
                @Html.DisplayFor(model => model.Description)
            }

2020-11-03 22:36 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Models/Task/TaskWithMembersViewModel.cs
> +        public TaskWithMembersViewModel(List <MemberForTaskModel> Members)
```suggestion
        public TaskWithMembersViewModel(List <MemberForTaskModel> members)

2020-11-03 22:41 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Helpers/HelperControllers.cs
> +            foreach (var userTask in userTasks)
foreach (var userTask in userTasks)
            {
                if (userTask.User != null)
                {
                    var member = allMembers.FirstOrDefault(user => user.UserId == userTask.UserId);
                    member.Selected = true;
                    member.UserTaskId = userTask.UserTaskId;
                }
            }

2020-11-03 22:42 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Helpers/HelperControllers.cs
> +            foreach (var userTask in userTasks)
```suggestion
            foreach (var userTask in userTasks)
            {
                if (userTask.User != null)
                {
                    taskMembers.Add(new MemberForTaskModel()
                    {
                        UserId = userTask.UserId,
                        FullName = userTask.User.Name + " " + userTask.User.LastName,
                        Selected = true,
                        UserTaskId = userTask.UserTaskId
                    });
                }
            }

2020-11-03 23:10 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/TaskRepository.cs
> +                .ThenInclude(userTask => userTask.User)
```suggestion
            var entity = await currentSet.FindAsync(id);
```
I fixed it in the following ways:
1. Added dependency to DataAccessLayer: _Microsoft.EntityFrameworkCore.Proxies_
2. Added option to AddDbContext: _UseLazyLoadingProxies()_
3. And of course deleted my kludge =)  ~~.Include(task => task.UserTask)~~

[Сommit with fix](https://github.com/Dev-incubator/DIMS-Core/pull/12/commits/6ea1eba16eef8dcc779d786eaf5b2f96ab94fde2)

Is it good now?

2020-11-04 05:43 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskController.cs
> +            model.Members.GetMembersForTask(task.UserTask);                                         // Get list of members who participates in this task
```suggestion
            var model = mapper.Map<TaskViewModel>(task);                                        
            ViewBag.AllMembers = await memberService.GetMembersViewModel(mapper);
            return View(model);
```

2020-11-04 05:45 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskController.cs
> +            model.Members.GetMembersForTask(task.UserTask);                                         // Get list of members who participates in this task
```suggestion
            var task = await taskService.GetTask(id);
            var model = mapper.Map<TaskViewModel>(task);
            ViewBag.AllMembers = await memberService.GetMembersViewModel(mapper);
```

2020-11-04 05:47 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskController.cs
> +            model.Members.MarkSelectedMembersForTask(task.UserTask);                                // Mark members who participates in this task
```suggestion         
            var task = await taskService.GetTask(id);
            var model = mapper.Map<TaskViewModel>(task);

            ViewBag.AllMembers = await memberService.GetMembersViewModel(mapper);
            return View(model);

2020-11-05 21:09 UTC, PushMeNow requested changes
Hi.
I did one comment. Fix it please

2020-11-05 21:09 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +            }
Why do you call changes saving in 'if' block? What will happen if `model.SelectedMembers` is null?

2020-11-05 22:27 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +            }
}
            }

            await unitOfWork.Save();

2020-11-06 18:02 UTC, PushMeNow approved these changes
Good job

2020-11-06 18:03 UTC, merged