The functionality of adding a user has been implemented
Dev-incubator/DIMS-Core pull request #13
Opened 2020-10-25 23:30 UTC by SashaDrapun

2020-10-27 12:07 UTC, PushMeNow requested changes
Hi.
Good job! I did a comment. Please fix it.

2020-10-27 12:07 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/MemberController.cs
> +        public MemberController(IMemberService memberService, IDirectionService directionService, IMapper mapper)
Could you move parameter on separate rows when quantity of params more than 2? It will look like better.

MethodName(
param1,
param2,
...etc
)

2020-10-28 01:23 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Controllers/MemberController.cs
> +        public MemberController(IMemberService memberService, IDirectionService directionService, IMapper mapper)
![image](https://user-images.githubusercontent.com/45926089/97379194-4b93a500-18d5-11eb-837e-83e8e45a2244.png)

2020-10-29 17:21 UTC, maximsan reviewed
Hello @SashaDrapun! I've left some minor comments. @PushMeNow Please, check that everything is resolved before merging. Thanks guys!

2020-10-29 17:21 UTC, maximsan commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IDirectionService.cs
> +        Task<DirectionModel> GetMember(int id);
I hope you was in rush and did it by mistake, but please, be careful. As I see it should be  `Get` or `GetDirection` according to the name of the service at least.

2020-10-29 17:21 UTC, maximsan commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IMemberService.cs
> +        Task<IEnumerable<VUserProfileModel>> Search();
Search or GetAll ?

2020-10-29 17:21 UTC, maximsan commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/DirectionService.cs
> +            var query = unitOfWork.DirectionRepository.GetAll();
`var directions`

2020-10-29 23:09 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IDirectionService.cs
> +        Task<DirectionModel> GetMember(int id);
![image](https://user-images.githubusercontent.com/45926089/97641865-f67e9d00-1a54-11eb-8604-20a6d8f96f98.png)

2020-10-29 23:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IMemberService.cs
> +        Task<IEnumerable<VUserProfileModel>> Search();
![image](https://user-images.githubusercontent.com/45926089/97641897-07c7a980-1a55-11eb-95b1-90a3c4aec4aa.png)

2020-10-29 23:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/DirectionService.cs
> +            var query = unitOfWork.DirectionRepository.GetAll();
![image](https://user-images.githubusercontent.com/45926089/97641952-2168f100-1a55-11eb-8079-e6f4c597b8f9.png)

2020-10-29 23:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/DirectionService.cs
> +            var mappedQuery = mapper.ProjectTo<DirectionModel>(query);
![image](https://user-images.githubusercontent.com/45926089/97641944-1e6e0080-1a55-11eb-802b-3fabb5882c05.png)

2020-10-31 22:22 UTC, leonidbogin approved these changes

2020-11-02 20:51 UTC, maximsan approved these changes
Fine. Thanks!

2020-11-03 09:56 UTC, PushMeNow approved these changes
Good job.

2020-11-03 09:57 UTC, merged