Task Track - Index
Dev-incubator/DIMS-Core pull request #15
Opened 2020-10-31 16:02 UTC by leonidbogin

![image](https://user-images.githubusercontent.com/65702576/97783606-ffcd4e00-1ba9-11eb-8b46-9b1e1f1942aa.png)

Used cherry pick for TaskController, Task/edit.cshtml, Task/details.cshtml. To add the ability to return to TaskTrack controller.
```suggestion
[HttpGet("details/{id}")]
public async Task<IActionResult> Details(int id, string back = null)
{
            ...
            ...
            ViewBag.backController = back;
            return View(model);
}
```
```suggestion
@await Html.PartialAsync("_BackToList", new BackToListViewModel { Controller = ViewBag.backController ?? "tasks" })
```

2020-10-31 19:43 UTC, SashaDrapun approved these changes
Good job

2020-11-03 10:40 UTC, PushMeNow requested changes
Hi.
I did some comments. Look them through and fix. Let me know if any questions.

2020-11-03 10:40 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/ITaskTrackService.cs
> +        Task<IEnumerable<VUserTrackModel>> GetAllForMember(int UserId);
Camelcase for method params.

2020-11-03 10:40 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/ITaskTrackService.cs
> +        Task<IEnumerable<VUserTrackModel>> GetAllForMember(int UserId);
Rename please method. If you are looking for by smth method name should be named respectively (example, GetAll**By**UserId).

2020-11-03 11:22 UTC, SashaDrapun approved these changes
Good Job!

2020-11-04 06:25 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/ITaskTrackService.cs
> +        Task<IEnumerable<VUserTrackModel>> GetAllForMember(int UserId);
```suggestion
        Task<IEnumerable<VUserTrackModel>> GetAllByUserId(int userId);

2020-11-05 21:11 UTC, PushMeNow approved these changes
Good job.

2020-11-05 22:22 UTC, merged