Task Track - Create
Dev-incubator/DIMS-Core pull request #16
Opened 2020-11-03 01:04 UTC by leonidbogin

![мммк](https://user-images.githubusercontent.com/65702576/97935470-b6d3f000-1d89-11eb-8bc6-198fdb86f077.PNG)

2020-11-03 11:32 UTC, SashaDrapun reviewed
Hello good job! I found a couple of shortcomings, please fix them, or explain.

2020-11-03 11:32 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/ITaskTrackService.cs
> +
The same remarks as Konstantin's. Camelcase for method params.

2020-11-03 11:32 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IUserTaskService.cs
> +        Task<IEnumerable<UserTaskModel>> GetAllForMember(int UserId);
Same remark. Camelcase for method params.

2020-11-03 11:32 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +        public TaskTrackController(ITaskTrackService taskTracksService, IUserTaskService userTaskService, IMapper mapper)
Split parameters into several lines if the number of parameters passed is more than 2.

2020-11-03 11:32 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var searchResult = await taskTracksService.GetAllForMember(UserId: userId);
Can't we pass the parameter in the usual way?

2020-11-04 06:41 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/ITaskTrackService.cs
> +
```suggestion
        Task<IEnumerable<VUserTrackModel>> GetAllByUserId(int userId);

2020-11-04 06:42 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IUserTaskService.cs
> +        Task<IEnumerable<UserTaskModel>> GetAllForMember(int UserId);
```suggestion

2020-11-04 06:47 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +        public TaskTrackController(ITaskTrackService taskTracksService, IUserTaskService userTaskService, IMapper mapper)
private readonly IUserTaskService userTaskService;
        private readonly IMapper mapper;

        public TaskTrackController(ITaskTrackService taskTracksService, 
            IUserTaskService userTaskService, IMapper mapper)

2020-11-04 06:50 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var searchResult = await taskTracksService.GetAllForMember(UserId: userId);
```suggestion
            var searchResult = await taskTracksService.GetAllByUserId(userId);
```

2020-11-05 21:46 UTC, PushMeNow requested changes
Hi.
I did comments. Fix them please.

2020-11-05 22:49 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IUserTaskService.cs
> +        Task<IEnumerable<UserTaskModel>> GetAllForMember(int UserId);
```suggestion
        Task<IEnumerable<UserTaskModel>> GetAllByUserId(int userId);

2020-11-05 22:50 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/UserTask/UserTaskModel.cs
> +        public virtual TaskModel Task { get; set; }
public TaskModel Task { get; set; }

2020-11-06 15:45 UTC, maximsan approved these changes
Looks good for me.

2020-11-06 18:04 UTC, PushMeNow approved these changes
Good job

2020-11-06 18:05 UTC, merged