Task Track - Details
Dev-incubator/DIMS-Core pull request #20
Opened 2020-11-06 21:30 UTC by leonidbogin

2020-11-06 21:36 UTC, SashaDrapun approved these changes
Good job. I didn't find any errors.

2020-11-07 16:16 UTC, maximsan requested changes

2020-11-07 16:16 UTC, maximsan commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            ViewBag.BackController = back;
Why do we need it everywhere ? As I understand it's back url. In this case please create a partial view for the `back url`

2020-11-09 19:43 UTC, PushMeNow approved these changes
No blockers from my side.

2020-11-11 09:40 UTC, merged