Task - My tasks
Dev-incubator/DIMS-Core pull request #21
Opened 2020-11-07 01:21 UTC by leonidbogin

2020-11-07 16:08 UTC, maximsan requested changes
Hello! Think about using one method for statuses. It seems like a lot of redundant code for my point of view.

2020-11-07 16:08 UTC, maximsan commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/Task/MyTaskModel.cs
> +    public class MyTaskModel
Why is it `My...` ?

2020-11-07 16:08 UTC, maximsan commented on DIMS-Core/DIMS-Core/Views/Task/MyTasks.cshtml
> +                            }
Please, make all buttons fixed size and add space between them

2020-11-07 16:08 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Interfaces/ITaskStateRepository.cs
> +        void SetFail(int userId, int taskId);
Why do we need 4 methods for this ? I believe you can use 1 method `SetStatus(int userId, int taskId, Status status)` for this everywhere with `Enum Status`

2020-11-08 12:42 UTC, SashaDrapun approved these changes
Good job!

2020-11-10 20:42 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/Task/MyTaskModel.cs
> +    public class MyTaskModel
I did rename MyTask -> CurrentTask
```suggestion
    public class CurrentTaskModel

2020-11-10 23:48 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.DataAccessLayer/Interfaces/ITaskStateRepository.cs
> +        void SetFail(int userId, int taskId);
```suggestion
        void SetState(int userId, int taskId, TaskStateEnum status);

2020-11-11 01:10 UTC, leonidbogin commented
![image](https://user-images.githubusercontent.com/65702576/98752701-c2e82f00-23d3-11eb-88fc-f84733a0e7f9.png)

2020-11-11 01:19 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Views/Task/MyTasks.cshtml
> +                            }
![image](https://user-images.githubusercontent.com/65702576/98753295-0d1de000-23d5-11eb-95d2-e16b00ae76f6.png)

2020-11-12 16:11 UTC, maximsan approved these changes
Hello! Looks better. @PushMeNow  please review.

2020-11-13 16:36 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.sqlproj
> +    <Build Include="Procedures\SetUserTaskAsActive.sql" />
```suggestion
    <Build Include="Procedures\SetUserTaskState.sql" />

2020-11-14 18:59 UTC, PushMeNow requested changes
Hi dude!
I did some comments. Let me know if any questions.

2020-11-14 18:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
Use await keyword.

2020-11-14 18:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
await

2020-11-14 18:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
await

2020-11-15 06:25 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
```suggestion
            var currentUser = await memberService.GetMemberByEmail(User.Identity.Name);

2020-11-15 06:25 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
```suggestion
            var currentUser = await memberService.GetMemberByEmail(User.Identity.Name);

2020-11-15 06:26 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
```suggestion
            var currentUser = await memberService.GetMemberByEmail(User.Identity.Name);

2020-11-16 19:01 UTC, merged