Page progress and page userTasks are created
Dev-incubator/DIMS-Core pull request #22
Opened 2020-11-08 16:00 UTC by SashaDrapun

2020-11-09 19:40 UTC, PushMeNow requested changes
Hi.
You did pretty huge issue. Pay attention that each level of application has to correspond with their task.

2020-11-09 19:40 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/MemberService.cs
> +        public async Task<IEnumerable<UserTask>> GetTasksByUserId(int userId)
Business logic cannot return objects of data access layer.

2020-11-09 19:40 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/Member/UserTasks.cshtml
> +﻿@model IEnumerable<DIMS_Core.DataAccessLayer.Entities.Task>
View can use only view models.

2020-11-09 19:40 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/_ViewImports.cshtml
> +@using DIMS_Core.DataAccessLayer.Entities
Views mustn't know about data access layer.

2020-11-17 15:55 UTC, maximsan approved these changes
Looks fine for me. But please resolve all previous notes

2020-11-20 12:57 UTC, leonidbogin approved these changes

2020-11-20 22:04 UTC, PushMeNow approved these changes
Approve

2020-11-20 22:04 UTC, merged