Use UserId from identity database
Dev-incubator/DIMS-Core pull request #24
Opened 2020-11-13 23:45 UTC by leonidbogin

2020-11-14 19:02 UTC, PushMeNow requested changes
Hi.
I did some comments. Look them through and fix.

2020-11-14 19:02 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
await

2020-11-14 19:02 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
await

2020-11-14 19:02 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
await

2020-11-14 19:02 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
await

2020-11-15 06:27 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
```suggestion
            var currentUser = await memberService.GetMemberByEmail(User.Identity.Name);

2020-11-15 06:27 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
```suggestion
            var currentUser = await memberService.GetMemberByEmail(User.Identity.Name);

2020-11-15 06:27 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
```suggestion
            var currentUser = await memberService.GetMemberByEmail(User.Identity.Name);

2020-11-15 06:27 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            var currentUser = memberService.GetMemberByEmail(User.Identity.Name).Result;
```suggestion
            var currentUser = await memberService.GetMemberByEmail(User.Identity.Name);

2020-11-17 16:03 UTC, maximsan requested changes
Hm, I guess you have to work on improvement

2020-11-17 16:03 UTC, maximsan commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +                return RedirectToAction("Index", "Home", new { });
Actually it's better to create `AuthAttribute` or `AuthMiddleware` to handle all auth related logic there before controller.. Please, discuss it with @PushMeNow

2020-11-17 16:03 UTC, maximsan commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            }
And you repeat the same logic in every method. Is it ok for you ? What do you think ?

2020-11-18 17:08 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +                return RedirectToAction("Index", "Home", new { });
https://github.com/Dev-incubator/DIMS-Core/pull/24/commits/e2ae2b625a627ecd32e0e39c38e38846b8a38df3

2020-11-18 17:08 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +                return RedirectToAction("Index", "Home", new { });
https://github.com/Dev-incubator/DIMS-Core/pull/24/commits/e2ae2b625a627ecd32e0e39c38e38846b8a38df3

2020-11-18 17:08 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Controllers/TaskTrackController.cs
> +            }
https://github.com/Dev-incubator/DIMS-Core/pull/24/commits/e2ae2b625a627ecd32e0e39c38e38846b8a38df3

2020-11-20 22:08 UTC, PushMeNow approved these changes
Approve

2020-11-23 14:20 UTC, merged