Seed data for the Database and Identity
Dev-incubator/DIMS-Core pull request #25
Opened 2020-11-16 02:35 UTC by leonidbogin

2020-11-16 02:41 UTC, leonidbogin commented
GitHub didn't list all files.
![image](https://user-images.githubusercontent.com/65702576/99207022-f2c97500-27cd-11eb-89bd-22300c62b3c6.png)
![image](https://user-images.githubusercontent.com/65702576/99207059-0b398f80-27ce-11eb-80a3-6d89f5de87a1.png)
![image](https://user-images.githubusercontent.com/65702576/99207106-24424080-27ce-11eb-9376-ddd1eab1f8e9.png)

2020-11-19 13:49 UTC, maximsan approved these changes
Looks good.

2020-11-20 12:36 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/SeedData/PostDeploy.sql
> +Go
Create a Post-Deployment Script. This script, when publishing, execute two scripts that will add the required data to the database.
[More about SeedData for VS Database Project.](https://keyholesoftware.com/2016/12/12/creating-a-sql-database-project-for-isolated-development/)

2020-11-20 12:44 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Identity/Entities/Role.cs
> +            NormalizedName = name;
This is a field from a class Microsoft.AspNetCore.Identity.IdentityRole.

Fixed by calling the parent constructor.
```suggestion
        public Role(string name) : base(name)
        {

        }
```

2020-11-20 22:36 UTC, PushMeNow requested changes
Hi.
I did some comments.

2020-11-20 22:36 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Identity/Initialize/IdentityInitializer.cs
> +            }
Could you move this repeatable action in method?

2020-11-20 22:36 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Identity/Initialize/IdentityInitializer.cs
> +            }
Need to move creating of user in action because it is repeated

2020-11-21 05:30 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Identity/Initialize/IdentityInitializer.cs
> +            }
```suggestion
        private static async Task CheckAndCreateRole(RoleManager<Role> roleManager, string name)
        {
            if (await roleManager.FindByNameAsync(name) is null)
            {
                await roleManager.CreateAsync(new Role(name));
            }
        }
```

2020-11-21 05:33 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Identity/Initialize/IdentityInitializer.cs
> +            }
```suggestion
        private static async Task CheckAndCreateUser(UserManager<User> userManager, string email, string password, 
string role)
        {
            if (await userManager.FindByNameAsync(email) is null)
            {
                var user = new User()
                {
                    Email = email,
                    UserName = email
                };
                var result = await userManager.CreateAsync(user, password);
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(user, role);
                }
            }
        }
```

2020-11-21 05:37 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Identity/Initialize/IdentityInitializer.cs
> +            }
https://github.com/Dev-incubator/DIMS-Core/pull/25/commits/f736bf5086948ce66479390c5879e23d11450480

2020-11-21 05:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Identity/Initialize/IdentityInitializer.cs
> +            }
https://github.com/Dev-incubator/DIMS-Core/pull/25/commits/ebdc77a4583bb0370cc22b7d9c2a2fea1ad40cf6

2020-11-22 19:40 UTC, PushMeNow approved these changes
Approve

2020-11-22 19:40 UTC, merged