Project design update (not flexible)
Dev-incubator/DIMS-Core pull request #26
Opened 2020-11-17 00:12 UTC by leonidbogin

# Task - Index
![Task-Index](https://user-images.githubusercontent.com/65702576/99322847-e4d52c00-2881-11eb-9d7a-d6690ca1dd40.png)

# Task - Create
![Task-Create](https://user-images.githubusercontent.com/65702576/99322825-dab32d80-2881-11eb-9363-8e3776150f24.png)

# Task - Edit
![Task-Edit](https://user-images.githubusercontent.com/65702576/99322842-e30b6880-2881-11eb-8a02-953cc0669af2.png)

# Task - Details
![Task-Details](https://user-images.githubusercontent.com/65702576/99322839-e0a90e80-2881-11eb-9717-b925414bd53b.png)

# Task - Delete
![Task-Delete](https://user-images.githubusercontent.com/65702576/99322833-de46b480-2881-11eb-825e-dc2735aea283.png)

# CurrentTask - Index
![CurrentTasks-Index](https://user-images.githubusercontent.com/65702576/99322502-1dc0d100-2881-11eb-9ee4-251ca4b84299.png)
`----------------------------------------------------------------------------------------------------------------------------`
# TaskTrack - Index
![TaskTrack-Index](https://user-images.githubusercontent.com/65702576/99322952-22d25000-2882-11eb-80cb-18928204e9f5.png)

# TaskTrack - Create
![TaskTrack-Create](https://user-images.githubusercontent.com/65702576/99322932-177f2480-2882-11eb-9baf-546e01a2ccc6.png)

# TaskTrack - Edit
![TaskTrack-Edit](https://user-images.githubusercontent.com/65702576/99322949-1f3ec900-2882-11eb-9485-40fcf122d95e.png)

# TaskTrack - Details
![TaskTrack-Details](https://user-images.githubusercontent.com/65702576/99322943-1c43d880-2882-11eb-94a3-18ed8e10b048.png)

# TaskTrack - Delete
![TaskTrack-Delete](https://user-images.githubusercontent.com/65702576/99322940-19e17e80-2882-11eb-95be-07971c60d9ae.png)
`----------------------------------------------------------------------------------------------------------------------------`
# Member - Index
![Member-Index](https://user-images.githubusercontent.com/65702576/99322635-67112080-2881-11eb-8f6c-eb0050d8880f.png)

# Member - Create
![Member-Create](https://user-images.githubusercontent.com/65702576/99322611-595b9b00-2881-11eb-987e-89e60af62979.png)

# Member - Edit
![Member-Edit](https://user-images.githubusercontent.com/65702576/99322622-5e204f00-2881-11eb-8e7b-ab788a441e04.png)

# Member - Delete
![Member-Delete](https://user-images.githubusercontent.com/65702576/99322608-56f94100-2881-11eb-85b1-7bbc0926c58b.png)

2020-11-17 20:04 UTC, maximsan requested changes
Looks fine for me except the question about repetitive code with back button. Can we improve it ?

2020-11-17 20:04 UTC, maximsan commented on DIMS-Core/DIMS-Core/Views/Task/Create.cshtml
>              </div>
Is it possible to use the code as partial view? It's repeated in several places.

2020-11-17 20:04 UTC, maximsan commented on DIMS-Core/DIMS-Core/wwwroot/css/site.css
> +    width: 70px;
it's preferable to use relative values as rem instead of px

2020-11-19 09:20 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/Views/Task/Create.cshtml
>              </div>
Done.
https://github.com/Dev-incubator/DIMS-Core/pull/26/commits/64fe4dd8de672e1e0ee03116700d34166e1c0b30
https://github.com/Dev-incubator/DIMS-Core/pull/26/commits/f85978b6736cc350354064f1650ccfe243ec73cc

2020-11-19 09:26 UTC, leonidbogin commented on DIMS-Core/DIMS-Core/wwwroot/css/site.css
> +    width: 70px;
Done.
https://github.com/Dev-incubator/DIMS-Core/pull/26/commits/a203e9ce4d1177a5b98efa093245f28fb27496d7

2020-11-20 22:44 UTC, PushMeNow approved these changes
Approve

2020-11-23 11:04 UTC, merged