Dev database
Dev-incubator/DIMS-Core pull request #4
Opened 2020-09-27 19:24 UTC by SashaDrapun

2020-09-28 17:26 UTC, PushMeNow requested changes
Hi!
I commented some changes. Please look them through and fix.

2020-09-28 17:26 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +		FORMAT(Task.DeadlineDate, 'dd.MM.yyyy hh:mm:ss') as DeadlineDate
Useless format. Database must use international format (yyyy-MM-dd). Remove format.

2020-09-28 17:26 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProfile.sql
> +		FORMAT(UserProfile.StartDate, 'dd.MM.yyyy', 'en-US') as UserProfile
Remove format

2020-09-28 17:26 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProgress.sql
> +		FORMAT(TaskTrack.TrackDate, 'dd.MM.yyyy hh:mm:ss') as TrackDate
Remove format

2020-09-28 17:26 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTask.sql
> +		FORMAT(Task.DeadlineDate, 'dd.MM.yyyy hh:mm:ss') as DeadlineDate,
Remove format

2020-09-28 17:26 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTrack.sql
> +		FORMAT(TaskTrack.TrackDate, 'dd.MM.yyyy hh:mm:ss') as TrackDate
Remove format

2020-09-28 17:41 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +		FORMAT(Task.DeadlineDate, 'dd.MM.yyyy hh:mm:ss') as DeadlineDate
Task.StartDate,
		Task.DeadlineDate

2020-09-28 17:43 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProfile.sql
> +		FORMAT(UserProfile.StartDate, 'dd.MM.yyyy', 'en-US') as UserProfile
UserProfile.[Address],
		UserProfile.MobilePhone,
		UserProfile.Skype,
		UserProfile.StartDate

2020-09-28 17:44 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProgress.sql
> +		FORMAT(TaskTrack.TrackDate, 'dd.MM.yyyy hh:mm:ss') as TrackDate
(UserProfile.[Name] + ' ' + UserProfile.LastName) as UserName,
		Task.[Name] as TaskName,
		TaskTrack.TrackNote,
		TaskTrack.TrackDate

2020-09-28 17:44 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTask.sql
> +		FORMAT(Task.DeadlineDate, 'dd.MM.yyyy hh:mm:ss') as DeadlineDate,
Task.StartDate,
		Task.DeadlineDate,

2020-09-28 17:44 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTrack.sql
> +		FORMAT(TaskTrack.TrackDate, 'dd.MM.yyyy hh:mm:ss') as TrackDate
TaskTrack.TrackNote,
		TaskTrack.TrackDate

2020-09-28 19:03 UTC, maximsan requested changes
Hello, guys. I left some notes. Good work!

2020-09-28 19:03 UTC, maximsan commented on DIMS-Core/DIMS-Core/Models/VUserProfile.cs
> +        public int? Age { get; set; }
Can the filed be null if the `BirthDate` is required in db ?

2020-09-28 20:23 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [LastName] NVARCHAR(255) NOT NULL,
[Name] NVARCHAR(64) NOT NULL, 
    [Email] NVARCHAR(255) NOT NULL, 
    [LastName] NVARCHAR(64) NOT NULL,

2020-09-28 20:37 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [MobilePhone] NVARCHAR(255) NOT NULL,
[Address] NVARCHAR(255) NOT NULL, 
    [MobilePhone] NVARCHAR(16) NOT NULL,

2020-09-28 20:41 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [Education] NVARCHAR(255) NOT NULL,
[Email] NVARCHAR(255) NOT NULL, 
    [LastName] NVARCHAR(64) NOT NULL, 
    [Sex] TINYINT NOT NULL, 
    [Education] NVARCHAR(128) NOT NULL,

2020-09-28 20:59 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [Skype] NVARCHAR(255) NOT NULL,
[Sex] TINYINT NOT NULL DEFAULT 0, 
    [Education] NVARCHAR(128) NULL, 
    [BirthOfDate] DATETIME NULL, 
    [UniversityAverageScore] FLOAT NULL, 
    [MathScore] FLOAT NULL, 
    [Address] NVARCHAR(128) NULL, 
    [MobilePhone] NVARCHAR(16) NULL, 
    [Skype] NVARCHAR(255) NULL, 
    [StartDate] DATETIME NULL,

2020-09-28 21:03 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [MathScore] FLOAT NOT NULL,
[Sex] TINYINT NOT NULL DEFAULT 0,        // Standard ISO/IEC 5218
[Education] NVARCHAR(128) NULL, 
[BirthOfDate] DATETIME NULL, 
[UniversityAverageScore] FLOAT NULL, 
[MathScore] FLOAT NULL, 
[Address] NVARCHAR(128) NULL, 
[MobilePhone] NVARCHAR(16) NULL, 
[Skype] NVARCHAR(255) NULL, 
[StartDate] DATETIME NULL,

2020-09-28 21:04 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [UniversityAverageScore] FLOAT NOT NULL,
[Sex] TINYINT NOT NULL DEFAULT 0,        // Standard ISO/IEC 5218
    [Education] NVARCHAR(128) NULL, 
    [BirthOfDate] DATETIME NULL, 
    [UniversityAverageScore] FLOAT NULL, 
    [MathScore] FLOAT NULL, 
    [Address] NVARCHAR(128) NULL, 
    [MobilePhone] NVARCHAR(16) NULL, 
    [Skype] NVARCHAR(255) NULL, 
    [StartDate] DATETIME NULL,

2020-09-28 21:46 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +		Task.[Description],
![222](https://user-images.githubusercontent.com/65702576/94489077-85955c80-01ec-11eb-84f4-4aa1bd1f39f0.JPG)
Without parentheses, these fields are highlighted as reserved names, but they work.
I will delete them.
```suggestion
	AS SELECT 
		Task.TaskId,
		Task.Name,
		Task.Description,
```

2020-09-28 21:54 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProfile.sql
> +		UserProfile.[Address],
```suggestion
		UserProfile.Address,
```

2020-09-28 22:33 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Models/DIMSContext.cs
> +    public partial class DIMSContext : DbContext
![Снимок](https://user-images.githubusercontent.com/45926089/94492781-b88f1e80-01f3-11eb-9f83-e08fa1115f6d.PNG)

2020-09-28 23:16 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProfile.sql
> +		((CONVERT(int,CONVERT(char(8),GETDATE(),112))-CONVERT(char(8),UserProfile.BirthOfDate,112))/10000) AS Age,
```suggestion
		(SELECT dbo.CalcFullAge(UserProfile.BirthOfDate)) AS Age,
```

2020-09-29 11:59 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Models/UserProfile.cs
> +        public DateTime StartDate { get; set; }
Add nullable types to necessary fields

2020-09-29 12:00 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Models/VUserProfile.cs
> +        public int? Age { get; set; }
BirthDate now can be nullable

2020-09-29 18:08 UTC, PushMeNow requested changes
Hi.
I did some comment. Look them through and fix please.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/Direction.cs
> +        public string? Description { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/Task.cs
> +        public string? Description { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/TaskTrack.cs
> +        public string? TrackNote { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/UserProfile.cs
> +        public byte Sex { get; set; }
Replace it by enum as i told you.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/UserProfile.cs
> +        public string? Education { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/UserProfile.cs
> +        public string? Skype { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VTask.cs
> +        public string? Description { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserProfile.cs
> +        public string? Education { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserProfile.cs
> +        public string? Skype { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserProfile.cs
> +        public byte Sex { get; set; }
Replace it by enum as i told you.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserProgress.cs
> +        public string? TrackNote { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserTask.cs
> +        public string? Description { get; set; }
String is nullable type by default.

2020-09-29 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserTrack.cs
> +        public string? TrackNote { get; set; }
String is nullable type by default.

2020-09-29 20:33 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/Task.sql
> +	[TaskId] INT Identity(1,1) NOT NULL PRIMARY KEY,
```suggestion
    [TaskId] INT Identity(1,1) NOT NULL PRIMARY KEY, 
```
The problem was with the tabs and spaces. In git, tabs consist of three spaces. 
The solution is to replace all tabs with four spaces.

2020-09-29 20:40 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +		Task.DeadlineDate
```suggestion
		TaskId,
		Name,
		Description,
		StartDate,
		DeadlineDate
```

2020-09-29 20:57 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [Email] NVARCHAR(255) NOT NULL,
```suggestion
    [Email] NVARCHAR(128) NOT NULL, 
```

2020-09-29 20:58 UTC, leonidbogin commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserProfile.sql
> +    [Skype] NVARCHAR(255) NULL,
```suggestion
    [Skype] NVARCHAR(128) NULL, 
```

2020-09-29 22:12 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserProgress.cs
> +        public string? TrackNote { get; set; }
Done

2020-09-29 22:13 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserProfile.cs
> +        public byte Sex { get; set; }
![image](https://user-images.githubusercontent.com/45926089/94622033-184ffd00-02ba-11eb-9ee5-261441e4881c.png)

2020-09-29 22:14 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/VUserProfile.cs
> +        public string? Skype { get; set; }
Donte

2020-09-29 22:14 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/Task.cs
> +        public string? Description { get; set; }
Done

2020-09-29 22:14 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/Direction.cs
> +        public string? Description { get; set; }
Done

2020-09-29 22:15 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Entities/UserProfile.cs
> +        public byte Sex { get; set; }
![image](https://user-images.githubusercontent.com/45926089/94622223-77157680-02ba-11eb-89ff-6b97acdea9b4.png)

2020-09-30 20:17 UTC, PushMeNow approved these changes

2020-09-30 20:18 UTC, merged