Dev business
Dev-incubator/DIMS-Core pull request #6
Opened 2020-10-06 19:40 UTC by SashaDrapun

Display and delete for members and tasks

2020-10-10 19:44 UTC, PushMeNow requested changes
Hi.
You did pretty good PR. There are some little issues. Fix them and I'll merge your changes.

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/MappingProfiles/MemberProfile.cs
> +                .ForMember(dest => dest.Email,
This mapping for Email is redundant.

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +            var entity = mapper.Map<DataAccessLayer.Entities.Task>(model);
Remove namespace please and rename type Task by keyword using.

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +                optionsBuilder.UseSqlServer(configuration.GetConnectionString("DIMSDatabase"));
Move this in startup.

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Models/Member/EditMemberViewModel.cs
> +    }
Where are validation attributes?

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Models/Member/MemberViewModel.cs
> +        public DateTime? StartDate { get; set; }
Validation attributes?

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Models/Task/TaskViewModel.cs
> +        public DateTime DeadlineDate { get; set; }
Validation attributes?

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/Member/Create.cshtml
> +    ViewData["Title"] = "View";
View?

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/Member/Create.cshtml
> +<h1>View</h1>
View?

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/Member/Create.cshtml
> +<h4>MemberModel</h4>
MemberModel?

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/Member/Delete.cshtml
> +    <h4>MemberModel</h4>
MemberModel?

2020-10-10 19:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core/Views/Member/Edit.cshtml
> +<h4>MemberModel</h4>
MemberModel?

2020-10-10 20:41 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +            var entity = mapper.Map<DataAccessLayer.Entities.Task>(model);
```suggestion
            var entity = mapper.Map<TaskEntities>(model);
```

2020-10-11 22:59 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/MappingProfiles/MemberProfile.cs
> +                .ForMember(dest => dest.Email,
![image](https://user-images.githubusercontent.com/45926089/95692447-8b4c6280-0c2e-11eb-8b4e-3caf49a9e3e5.png)

2020-10-11 23:09 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Views/Member/Edit.cshtml
> +<h4>MemberModel</h4>
H4 removed from layout

2020-10-11 23:09 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Views/Member/Delete.cshtml
> +    <h4>MemberModel</h4>
H4 removed from layout

2020-10-11 23:11 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Views/Member/Create.cshtml
> +<h4>MemberModel</h4>
H4 removed from layout

2020-10-11 23:16 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Views/Member/Create.cshtml
> +    ViewData["Title"] = "View";
![image](https://user-images.githubusercontent.com/45926089/95692777-f5660700-0c30-11eb-999d-ed84f89f3dd3.png)

2020-10-11 23:16 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Views/Member/Create.cshtml
> +<h1>View</h1>
![image](https://user-images.githubusercontent.com/45926089/95692779-feef6f00-0c30-11eb-822e-d1d019f07789.png)

2020-10-11 23:30 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Models/Member/EditMemberViewModel.cs
> +    }
Some Validation attributes were added. More validation attributes will be added during development
![image](https://user-images.githubusercontent.com/45926089/95693029-bf298700-0c32-11eb-8c22-c15bed8feb7e.png)

2020-10-12 12:44 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core/Models/Member/MemberViewModel.cs
> +        public DateTime? StartDate { get; set; }
This model is only used for display data

2020-10-14 21:59 UTC, PushMeNow requested changes
Hi.
You didn't resolve one issue about connection string.

2020-10-14 21:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +                optionsBuilder.UseSqlServer(configuration.GetConnectionString("DIMSDatabase"));
I repeat: move this line in Startup.

2020-10-18 15:32 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +                optionsBuilder.UseSqlServer(configuration.GetConnectionString("DIMSDatabase"));
![image](https://user-images.githubusercontent.com/45926089/96372608-44032c00-1170-11eb-8af2-810d02bc6570.png)

2020-10-18 15:32 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +                optionsBuilder.UseSqlServer(configuration.GetConnectionString("DIMSDatabase"));
![image](https://user-images.githubusercontent.com/45926089/96372616-4feeee00-1170-11eb-82e0-472762f9ca67.png)

2020-10-20 10:27 UTC, PushMeNow requested changes
Hello.
There is a little issue. Look at my comment and fix it.

2020-10-20 10:27 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +        private readonly IConfiguration configuration;
Remove configiration. You don't use it in this class

2020-10-20 21:21 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +        private readonly IConfiguration configuration;
![image](https://user-images.githubusercontent.com/45926089/96645482-4a8dd100-1333-11eb-978d-5c0d673b40f8.png)

2020-10-21 11:00 UTC, PushMeNow approved these changes

2020-10-21 11:01 UTC, merged