VUserProfileRepositoryTest
Dev-incubator/DIMS-Core pull request #7
Opened 2020-10-09 16:07 UTC by leonidbogin

- I created a DIMS-Core.DataAccessLayer.Tests project to test the DIMS-Core.DataAccessLayer.
- I created Infrastructure/RepositoryTestBase. Where the connection to InMemoryDatabase and SeedData are stored.
- I created VUserProfileRepositoryTests with 2 view tests (ReturnAll, ReturnById).

2020-10-11 17:16 UTC, PushMeNow requested changes
Hi man! :)
I looked your changes through. Pretty good work. But there are some issues. Resolve them and I'll merge your commit.

2020-10-11 17:16 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestBase.cs
> +    public class RepositoryTestBase : IDisposable
Use TestFixture and OneTimeTearDown attributes for object disposing after executing of all tests.

2020-10-11 17:16 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +            var result = await query.GetByIdAsync(newId);               //get
Save method?

2020-10-11 17:16 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +            var result = await query.GetByIdAsync(updateId);            //get
Save method?

2020-10-11 17:57 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +            var result = await query.GetByIdAsync(newId);               //get
```suggestion
            await query.CreateAsync(newUserProfile);                    //add
            context.SaveChanges();
            var result = await query.GetByIdAsync(newId);               //get
```

2020-10-11 17:59 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +            var result = await query.GetByIdAsync(updateId);            //get
```suggestion
            query.Update(updateUserProfile);                            //update
            context.SaveChanges();
            var result = await query.GetByIdAsync(updateId);            //get
```

2020-10-11 18:20 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestBase.cs
> +    public class RepositoryTestBase : IDisposable
```suggestion
namespace DIMS_Core.Tests.DataAccessLayer.Infrastructure
{
    [TestFixture]
    public class RepositoryTestBase : IDisposable
```
```suggestion

        [OneTimeTearDown]
        public void Dispose()
        {
            context.Database.EnsureDeleted();
            context.Dispose();
        }
```

2020-10-12 12:48 UTC, SashaDrapun reviewed
I think all is good :) I wrote my part of the tests by analogy with these tests

2020-10-13 15:08 UTC, maximsan approved these changes
I left some recommendations regarding tests. Let me know if smth is still not clear. Please follow them. Thanks for you work. It looks really good!

2020-10-13 15:08 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +            Assert.AreEqual(countUsers, result.Count());
```
var actualCount = list.Count();

// Assert
Assert.That(actualCount, Is.EqualTo(expectedCount));

```

It's more clear assertion from my perspective, try to use this NUnit notation everywhere
https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html

2020-10-13 15:08 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +            await query.CreateAsync(newUserProfile);                    //add
I propose you to delete comments as _add,  get and etc_, because the are useless. In other case make them more clear and descriptive if you really need them.

2020-10-14 22:06 UTC, PushMeNow approved these changes

2020-10-14 22:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +            var query = new UserProfileRepository(context);
It's better to move initialization in constructor and use initialized object.

2020-10-14 22:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserProfileRepositoryTests.cs
> +            var query = new VUserProfileRepository(context);
Again better move initialization in constructor.

2020-10-14 22:07 UTC, merged