Alexander drapun/main utest
Dev-incubator/DIMS-Core pull request #8
Opened 2020-10-11 22:49 UTC by SashaDrapun

Tests of the following repositories: DirectionRepository, TaskRepository, TaskStateRepository, VTaskRepository, VUserTask, VUserTrack

2020-10-11 23:38 UTC, leonidbogin reviewed
The code is similar to mine, so I can't find errors =)
Only found an unnecessary use of xunit.

2020-10-11 23:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DIMS-Core.Tests.csproj
> +    <PackageReference Include="xunit.extensibility.core" Version="2.4.1" />
Two similar libraries nunit and xunit are included.
I think only Nunit is necessary.
![image](https://user-images.githubusercontent.com/65702576/95692927-0b27fc00-0c32-11eb-80e7-7c709c2aabf8.png)

2020-10-11 23:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +using Xunit;
Also included are two similar libraries nunit and xunit.

2020-10-11 23:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +using Xunit;
Also included are two similar libraries nunit and xunit.

2020-10-11 23:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskStateRepositoryTest.cs
> +using Xunit;
Also included are two similar libraries nunit and xunit.

2020-10-11 23:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +using Xunit;
Also included are two similar libraries nunit and xunit.

2020-10-11 23:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +using Xunit;
Also included are two similar libraries nunit and xunit.

2020-10-11 23:38 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +using Xunit;
Also included are two similar libraries nunit and xunit.

2020-10-12 00:02 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DIMS-Core.Tests.csproj
> +    <PackageReference Include="xunit.extensibility.core" Version="2.4.1" />
XUnit dependency was removed
![image](https://user-images.githubusercontent.com/45926089/95693859-437e0900-0c37-11eb-8b02-3b027b5ca6de.png)

2020-10-12 00:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +using Xunit;
Removed unnecessary using of xunit from all test classes

2020-10-12 00:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +using Xunit;
Removed unnecessary using of xunit from all test classes

2020-10-12 00:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +using Xunit;
Removed unnecessary using of xunit from all test classes

2020-10-12 00:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskStateRepositoryTest.cs
> +using Xunit;
Removed unnecessary using of xunit from all test classes

2020-10-12 00:11 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +using Xunit;
Removed unnecessary using of xunit from all test classes

2020-10-12 00:11 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +using Xunit;
Removed unnecessary using of xunit from all test classes

2020-10-13 15:35 UTC, maximsan requested changes
Hello. I left some the same notes to you as to Leonid. BTW, please add some test for negative cases, all your test suites has only successful tests. For example if you trying to delete or to update not existed user, or if you are trying to get the user from DB by not existed id. Anyway good work. Thanks!

2020-10-13 15:35 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +        private DbContextOptions<DIMSCoreDatabaseContext> options;
Can it be read only too ?

2020-10-13 15:35 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestBase.cs
> +            var vUserProfiles = new VUserProfile[3];
I believe you can use context.VUserProfile.Add(...) here directly in cycle and do not create extra variable, can't you ?

2020-10-13 15:35 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            Assert.AreEqual(countDirections, result.Count());
```
var actualCount = list.Count();

// Assert
Assert.That(actualCount, Is.EqualTo(expectedCount));
```

It's more clear assertion from my perspective, try to use this NUnit notation everywhere
https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html

2020-10-13 15:35 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +            TaskEntity result = await query.GetByIdAsync(deleteId);    //get
use _var_

2020-10-15 17:59 UTC, PushMeNow requested changes
Hi.
Please look my comments through and make changes.

2020-10-15 17:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            var query = new DirectionRepository(context);
Move all initializations of repository in constructor.

2020-10-18 14:28 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
> +        private DbContextOptions<DIMSCoreDatabaseContext> options;
![image](https://user-images.githubusercontent.com/45926089/96370670-55940600-1167-11eb-9024-0fafddf6fdbb.png)

2020-10-18 14:32 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestBase.cs
> +            var vUserProfiles = new VUserProfile[3];
![image](https://user-images.githubusercontent.com/45926089/96370834-e66ae180-1167-11eb-97a8-02b0abebb3b0.png)

2020-10-18 14:41 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            Assert.AreEqual(countDirections, result.Count());
![image](https://user-images.githubusercontent.com/45926089/96371196-3302ec80-1169-11eb-92d6-3e7165134b2c.png)

2020-10-18 14:48 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            var result = await query.GetByIdAsync(updateId);            //get
![image](https://user-images.githubusercontent.com/45926089/96371370-203ce780-116a-11eb-9457-c6a08ee067a9.png)

2020-10-18 14:51 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +            TaskEntity result = await query.GetByIdAsync(deleteId);    //get
![image](https://user-images.githubusercontent.com/45926089/96371472-7f026100-116a-11eb-97c4-25481a17f506.png)

2020-10-18 15:10 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +            var query = new DirectionRepository(context);
![image](https://user-images.githubusercontent.com/45926089/96371965-3ef0ad80-116d-11eb-876d-62955e02a9d6.png)

2020-10-20 10:25 UTC, PushMeNow requested changes
Hi man!
I did some comments. It is about naming so will not difficult to fix it.

2020-10-20 10:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +        public void CleanupQuery()
It is not query

2020-10-20 10:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +            query = new VUserTaskRepository(Context);
It is not query

2020-10-20 10:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +        public void CleanupQuery()
It is not query

2020-10-20 10:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +            query = new VUserTrackRepository(Context);
It is not query

2020-10-20 10:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +        public void CleanupQuery()
It is not query

2020-10-20 21:39 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +        }
![image](https://user-images.githubusercontent.com/45926089/96647128-d3a60780-1335-11eb-9d24-8b7b3575bf75.png)

2020-10-20 21:39 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/DirectionRepositoryTest.cs
> +        public void CleanupQuery()
![image](https://user-images.githubusercontent.com/45926089/96647202-ed474f00-1335-11eb-9d9e-c67ed8ee361e.png)

2020-10-20 21:40 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +        public void CleanupQuery()
![image](https://user-images.githubusercontent.com/45926089/96647237-f6382080-1335-11eb-8ea6-f5dc6188b05d.png)

2020-10-20 21:40 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VTaskRepositoryTests.cs
> +        public void CleanupQuery()
![image](https://user-images.githubusercontent.com/45926089/96647250-fcc69800-1335-11eb-8b1d-1cc72b761a3a.png)

2020-10-20 21:40 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +        public void CleanupQuery()
![image](https://user-images.githubusercontent.com/45926089/96647267-018b4c00-1336-11eb-906d-4c68064ac878.png)

2020-10-20 21:40 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTaskRepositoryTest.cs
> +            query = new VUserTaskRepository(Context);
![image](https://user-images.githubusercontent.com/45926089/96647281-06500000-1336-11eb-9b54-8c5424923d1c.png)

2020-10-20 21:40 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +        public void CleanupQuery()
![image](https://user-images.githubusercontent.com/45926089/96647299-0a7c1d80-1336-11eb-8991-f79da3500b02.png)

2020-10-20 21:40 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/VUserTrackRepositoryTest.cs
> +            query = new VUserTrackRepository(Context);
![image](https://user-images.githubusercontent.com/45926089/96647315-11a32b80-1336-11eb-90c2-d8892a75909c.png)

2020-10-20 21:41 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskRepositoryTests.cs
> +            query = new TaskRepository(Context);
![image](https://user-images.githubusercontent.com/45926089/96647331-17990c80-1336-11eb-8860-04d235a88b3f.png)

2020-10-20 21:45 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.DataAccessLayer/Context/DIMSCoreDatabaseContext.cs
>          private readonly IConfiguration configuration;
![image](https://user-images.githubusercontent.com/45926089/96647627-b32a7d00-1336-11eb-841c-515c4733bd85.png)

2020-10-24 20:39 UTC, maximsan reviewed
Hello! You still have some unresolved questions. Please, resolve them

2020-10-25 23:44 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/MemberService.cs
> +            var query = unitOfWork.VUserProfileRepository.GetAll();
![image](https://user-images.githubusercontent.com/45926089/97122202-29fbb780-1735-11eb-9d3a-e0691faefe4a.png)

2020-10-25 23:44 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/TaskService.cs
> +            var query = unitOfWork.VTaskRepository.GetAll();
![image](https://user-images.githubusercontent.com/45926089/97122204-3718a680-1735-11eb-9a84-e48fafaa9b23.png)

2020-10-25 23:45 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestBase.cs
> +        protected DIMSCoreDatabaseContext Context;
![image](https://user-images.githubusercontent.com/45926089/97122212-47308600-1735-11eb-9fd9-aba9b4d4ff26.png)

2020-10-25 23:46 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestBase.cs
> +        protected DIMSCoreDatabaseContext Context;
It should be protected because we use this variable in inherited classes

2020-10-26 09:55 UTC, maximsan commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestBase.cs
> +        protected DIMSCoreDatabaseContext Context;
Ok! But don't forget to name it correctly

2020-10-27 10:47 UTC, PushMeNow approved these changes
PR was checked and approved.

2020-10-29 17:53 UTC, maximsan approved these changes
Please be accurate with naming all the time. It's approved

2020-10-29 17:53 UTC, merged