Unit Testing - Finished my part of tests for repositories
Dev-incubator/DIMS-Core pull request #9
Opened 2020-10-18 18:52 UTC by leonidbogin

2020-10-18 18:57 UTC, leonidbogin commented
All my tests are working
![image](https://user-images.githubusercontent.com/65702576/96377210-cac60200-118c-11eb-911b-d3f0e5963eb6.png)

2020-10-18 19:30 UTC, SashaDrapun reviewed
Hi, I have noted the points that seemed to me wrong

2020-10-18 19:30 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        private TaskTrackRepository query;
I think this field should be readonly

2020-10-18 19:30 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +            Assert.That(expected, Is.EqualTo(actual.Count()));
I consider code comments unnecessary

2020-10-18 19:30 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +            string expected = "New track note";
Strings can be made constants for optimization

2020-10-19 09:49 UTC, SashaDrapun commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +
User Assert.That(actual, Is.Null)

2020-10-20 10:44 UTC, PushMeNow requested changes
Hi man!
I did some comments. Look them through and fix.

2020-10-20 10:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        private TaskTrackRepository query;
It is not query

2020-10-20 10:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        public void CleanupQuery()
It is not query

2020-10-20 10:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        public void CreateAsync_Null_NotThrow()
Async??

2020-10-20 10:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +        public void CreateAsync_Null_NotThrow()
Async??

2020-10-20 10:44 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserTaskRepositoryTest.cs
> +        public void CreateAsync_Null_NotThrow()
Async??

2020-10-22 15:00 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +            Assert.That(expected, Is.EqualTo(actual.Count()));
I removed arrange, act, assert comments

2020-10-22 15:05 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +            string expected = "New track note";
I changed string to const string

2020-10-22 15:09 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +
I changed Assert.IsNull(actual) to Assert.That(actual, Is.Null).

2020-10-22 15:16 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        private TaskTrackRepository query;
I changed query to repository

2020-10-22 15:16 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        public void CleanupQuery()
I changed query to repository

2020-10-22 15:20 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        public void CreateAsync_Null_NotThrow()
CreateAsync is method's name (<Method>_<Action>_<Result>)

2020-10-22 15:21 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +        public void CreateAsync_Null_NotThrow()
CreateAsync is method's name (Method_Action_Result)

2020-10-22 15:21 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserTaskRepositoryTest.cs
> +        public void CreateAsync_Null_NotThrow()
CreateAsync is method's name (Method_Action_Result)

2020-10-22 15:56 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/TaskTrackRepositoryTest.cs
> +        public void CreateAsync_Null_NotThrow()
Сhanged the name of the test method to the correct:
public void CreateAsync_WithNullEntryShouldReturn_NotThrow()

2020-10-22 15:56 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserProfileRepositoryTests.cs
> +        public void CreateAsync_Null_NotThrow()
Сhanged the name of the test method to the correct:
public void CreateAsync_WithNullEntryShouldReturn_NotThrow()

2020-10-22 15:57 UTC, leonidbogin commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Repositories/UserTaskRepositoryTest.cs
> +        public void CreateAsync_Null_NotThrow()
Сhanged the name of the test method to the correct:
public void CreateAsync_WithNullEntryShouldReturn_NotThrow()

2020-10-24 05:37 UTC, merged